# Juno Release
heat_template_version: 2014-10-16

description: 'Install a basic Ubuntu server. '

parameters:

  key_name:
    type: string
    label: Key Name
    description: Name of an existing KeyPair to enable SSH access to the instances. 
    
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    default: ubuntu-14.10
    constraints:
        - allowed_values: [ ubuntu-12.04, ubuntu-14.04, ubuntu-14.10 ]
          description: Value must be one of ubuntu-12.04, ubuntu-14.04, ubuntu-14.10.
    
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used. 
    default: m2.small
    constraints:
        - allowed_values: [m2.small, m1.small, m1.medium, m1.large, m1.xlarge ]
          description: Value must be one of m1.small, m1.medium, m1.large or m1.xlarge.

resources:

  basic_server:
        type: OS::Nova::Server
        properties:
            key_name: { get_param: key_name }
            image: 
                "Fn::Select":
                    - { get_param: image_id }
                    -   
                        ubuntu-12.04: "c395c528-fb43-4066-9536-cf5c5efe806d"
                        ubuntu-14.04: "eeedf697-5a41-4d91-a478-01bb21e32cbe"
                        ubuntu-14.10: "fc48b5bb-e67d-4e39-b9ba-b6725c8b0c88"
            flavor: { get_param: instance_type }
            image_update_policy: REPLACE
            user_data_format: RAW

    
outputs:
    instance_ip:
        description: The IP address of the deployed instance.
        value: { get_attr: [basic_server, first_address] }
