HeatTemplateFormatVersion: '2012-12-12'

Description: >
  NeCTAR Sample Template showing how to create a Gluster client instance, with a Cinder volume attached to the instance.

Parameters:
  KeyName:
    Type: String
    Description:
      Name of an existing key pair to enable SSH access to the instance.
  InstanceType:
    Type: String
    Description: Type of the instance to be created.
    Default: m1.small
    AllowedValues: [m1.small, m1.medium, m1.large, m1.xlarge, m1.xxlarge]
  AvailabilityZone:
    Type: String
    Description: The NeCTAR zone in which the VM is to run (must have block storage)
    Default: melbourne-np
    AllowedValues: [melbourne-qh2, melbourne-np, monash, qld]

Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable ssh access and icmp"
      SecurityGroupIngress:
        -
          IpProtocol: "icmp"
          FromPort: "-1"
          ToPort: "-1"
          CidrIp: "0.0.0.0/0"
        -
          IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"
  NovaInstance:
    Type: OS::Nova::Server
    Properties:
      availability_zone: { Ref: AvailabilityZone }
      # this is currently the only ubuntu instance with the heat tools installed
      # given that we don't really use them, is it needed?
      image: "6464e3f6-3e39-4b78-811f-de6511b42585"
      flavor: { Ref: InstanceType }
      key_name: { Ref: KeyName }
      security_groups:
        - { Ref: SecurityGroup }
      user_data:
        Fn::Base64:
          Fn::Replace:
          - mount_directory: "/export/gvl-vol-replica"
          - |
            #!/bin/bash -v
            add-apt-repository ppa:semiosis/ubuntu-glusterfs-3.4
            apt-get update
            apt-get install -y glusterfs-server xfsprogs
            # if we copy a volume no need for this line...
            #mkfs.xfs -i size=512 /dev/vdc
            mkdir -p mount_directory
            mount /dev/vdc mount_directory

  CinderVolume:
    Type: OS::Cinder::Volume
    Properties:
      # small, but this is just a demo
      size: "2"
      availability_zone: { Ref: AvailabilityZone }
      # we will copy this volume full of data: in that way we don't have to rebuild it
      source_volid: 11be09d6-52f4-4443-a0a5-f5618775ea24
  VolumeAttachment:
    Type: OS::Cinder::VolumeAttachment
    Properties:
      volume_id: { Ref: CinderVolume }
      instance_uuid: { Ref: NovaInstance }
      mountpoint: /dev/vdc

Outputs:
  InstanceIP:
    Description: Public IP address of the newly created Gluster client instance.
    Value:
      Fn::GetAtt:
      - NovaInstance
      - first_address

